### ISSUE TITLE
安卓15闪退

### ISSUE THREAD

**Issue by Hsiao-Jan** [duzhaokun123/FuckCainiao#7]
菜鸟8.9.1105版本，用的最新模块，lspatch补丁的，打开就闪退大佬知道怎么回事吗？我lspatch用其他app不会闪退。
橘子5系统，底层安卓15。

**Comment by duzhaokun123** [comment]
闪退发日志

**Comment by Hsiao-Jan** [comment]
> 闪退发日志

能大概说一下怎么捕获日志吗？我复现一下

**Comment by Hsiao-Jan** [comment]
> 闪退发日志

麻烦帮忙看一下 我用adb获取了一下
```
11-16 12:12:11.248 I/Step_LSC(30872): 1500008320|R|I|onSStepChgd 26128 se 0
11-16 12:12:14.906 I/com.wangc.bill( 6246): dgc_arg: 2048KB,16MB,0.75
11-16 12:12:17.533 V/ActivityThread(13120): updateVmProcessStateForGc sceneId =1000 state=83886080
11-16 12:12:17.533 I/ainiao.wireless(13120): dgc_arg: has_act=1, state=1
11-16 12:12:17.548 D/vulkan  (13120): searching for layers in '/data/app/~~dGaTmAvYfQ2xGL4kMgpVOA==/com.cainiao.wireless-ZKCG7b49aNTrAOfp-nd42A==/lib/arm64'
11-16 12:12:17.549 D/vulkan  (13120): searching for layers in '/data/user/0/com.cainiao.wireless/cache/lspatch/origin/3918701720.apk!/lib/arm64-v8a'
11-16 12:12:17.555 D/MMUD    (13120): mtk_memory_debug_init com.cainiao.wireless 0x7619ae3200
11-16 12:12:17.557 V/ActivityThread(13120): updateVmProcessStateForGc sceneId =1000 state=83886080
11-16 12:12:17.557 I/ainiao.wireless(13120): dgc_arg: has_act=1, state=1
11-16 12:12:17.574 W/SoLoader(13120): >>>>>> Start init WelcomeActivity <<<<<<
11-16 12:12:17.574 W/SoLoader(13120): isAppRunningByDualaid, dataDir: /data/user/0/com.cainiao.wireless
11-16 12:12:17.574 D/TAG     (13120): CnRtbAdController: WelcomeActivity onCreate
11-16 12:12:17.577 D/MTK_COMPILER_OPT(13120): Conctrol flag is 0 for MTKInlineSIMD
11-16 12:12:17.577 D/MTK_COMPILER_OPT(13120): Disable MTKInlineSIMD
11-16 12:12:17.594 E/UTAnalytics(13120): getDefaultTracker error,must call setRequestAuthentication method first
11-16 12:12:17.595 W/System.err(13120): java.lang.RuntimeException: getDefaultTracker error,must call setRequestAuthentication method first
11-16 12:12:17.595 W/System.err(13120): 	at com.ut.mini.UTAnalytics.getDefaultTracker(SourceFile:544)
11-16 12:12:17.595 W/System.err(13120): 	at com.cainiao.wireless.timeline.a.c(SourceFile:377)
11-16 12:12:17.595 W/System.err(13120): 	at com.cainiao.wireless.timeline.a.aKS(SourceFile:402)
11-16 12:12:17.595 W/System.err(13120): 	at com.cainiao.wireless.timeline.TimeLineReportLifecycleCallbacks.enterBackground(SourceFile:96)
11-16 12:12:17.595 W/System.err(13120): 	at com.cainiao.wireless.timeline.TimeLineReportLifecycleCallbacks.onReceive(SourceFile:85)
11-16 12:12:17.595 W/System.err(13120): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1902)
11-16 12:12:17.595 W/System.err(13120): 	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
11-16 12:12:17.595 W/System.err(13120): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
11-16 12:12:17.595 W/System.err(13120): 	at android.os.Handler.handleCallback(Handler.java:1014)
11-16 12:12:17.595 W/System.err(13120): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 12:12:17.595 W/System.err(13120): 	at android.os.Looper.loopOnce(Looper.java:250)
11-16 12:12:17.595 W/System.err(13120): 	at android.os.Looper.loop(Looper.java:340)
11-16 12:12:17.595 W/System.err(13120): 	at android.app.ActivityThread.main(ActivityThread.java:9843)
11-16 12:12:17.595 W/System.err(13120): 	at java.lang.reflect.Method.invoke(Native Method)
11-16 12:12:17.595 W/System.err(13120): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:621)
11-16 12:12:17.595 W/System.err(13120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
11-16 12:12:17.602 D/ViewRootImpl(13120): AppSizeAfterRelayout, size: Point(1484, 1388), rotation: ROTATION_0
11-16 12:12:17.602 D/BufferQueueConsumer(13120): [](id:334000000001,api:0,p:-1,c:13120) connect: controlledByApp=false
11-16 12:12:17.603 D/BLASTBufferQueue(13120): [VRI[WelcomeActivity]#1](f:0,a:0) constructor()
11-16 12:12:17.603 D/BLASTBufferQueue(13120): [VRI[WelcomeActivity]#1](f:0,a:0) update width=1484 height=1388 format=-2 mTransformHint=0
11-16 12:12:17.613 D/BLASTBufferQueue(13120): [VRI[WelcomeActivity]#1](f:0,a:1) acquireNextBufferLocked size=1484x1388 mFrameNumber=1 applyTransaction=false mTimestamp=121610913393633(auto) mPendingTransactions.size=0 graphicBufferId=56349970923525 transform=0
11-16 12:12:18.833 D/VRI[WelcomeActivity](13120): visibilityChanged oldVisibility=true newVisibility=false
11-16 12:12:18.843 D/ViewRootImpl(13120): AppSizeAfterRelayout, size: Point(1484, 1388), rotation: ROTATION_0
11-16 12:12:18.843 D/BLASTBufferQueue(13120): [VRI[WelcomeActivity]#1](f:0,a:2) destructor()
11-16 12:12:18.843 D/BufferQueueConsumer(13120): [VRI[WelcomeActivity]#1(BLAST Consumer)1](id:334000000001,api:0,p:-1,c:13120) disconnect
11-16 12:12:18.845 E/WindowManager(13120): android.view.WindowLeaked: Activity com.cainiao.wireless.homepage.view.activity.WelcomeActivity has leaked window com.android.internal.policy.DecorView{d476f46 V.ED..... R.....ID 0,0-1260,1164}[WelcomeActivity] that was originally added here
11-16 12:12:18.845 E/WindowManager(13120): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1387)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1373)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:459)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:169)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.Dialog.show(Dialog.java:425)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.cainiao.commonlibrary.popupui.dialog.GuoguoCommonDialog.show(SourceFile:112)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.cainiao.wireless.homepage.view.activity.WelcomeActivity.showFirstDialog(SourceFile:369)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.cainiao.wireless.homepage.view.activity.WelcomeActivity.handlePrivacyProtect(SourceFile:330)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.cainiao.wireless.homepage.view.activity.WelcomeActivity.onCreate(SourceFile:145)
11-16 12:12:18.845 E/WindowManager(13120): 	at java.lang.reflect.Method.invoke(Native Method)
11-16 12:12:18.845 E/WindowManager(13120): 	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
11-16 12:12:18.845 E/WindowManager(13120): 	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(SourceFile:82)
11-16 12:12:18.845 E/WindowManager(13120): 	at LSPHooker_.onCreate(Unknown Source:11)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.Activity.performCreate(Activity.java:9359)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.Activity.performCreate(Activity.java:9311)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4613)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3063)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.os.Handler.dispatchMessage(Handler.java:109)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.os.Looper.loopOnce(Looper.java:250)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.os.Looper.loop(Looper.java:340)
11-16 12:12:18.845 E/WindowManager(13120): 	at android.app.ActivityThread.main(ActivityThread.java:9843)
11-16 12:12:18.845 E/WindowManager(13120): 	at java.lang.reflect.Method.invoke(Native Method)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:621)
11-16 12:12:18.845 E/WindowManager(13120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
11-16 12:12:18.845 W/WindowOnBackDispatcher(13120): sendCancelIfRunning: isInProgress=false callback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@4b32c9

```
